# Generated by Django 3.2.9 on 2021-11-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0007_alter_student_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjects'),
        ),
    ]
