# Generated by Django 3.2.9 on 2021-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_no',
            field=models.CharField(default='9', max_length=25),
            preserve_default=False,
        ),
    ]
