# Generated by Django 3.2.9 on 2021-11-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_assignment_choice_gradedassignment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='assignment',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='subjects.assignment'),
        ),
    ]
