# Generated by Django 3.2.9 on 2021-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_gradedassignment_unique_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
