# Generated by Django 3.2.9 on 2021-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_gradedassignment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedassignment',
            name='img',
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='img_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
